### ISSUE TITLE
Possibly Clarify Esprima-based Parsers vs. Others

### ISSUE THREAD

**Issue by xjamundx** [TheLarkInn/js-parser-discussions#7]
There is a core group of parsers that basically follow the API and AST from Esprima. When people talk about JS parsers I pretty much just think about this fairly short list:
- espree
- esprima
- acorn
- babylon*

And then there are other parsers of various kinds that aren't really compatible for various reasons. You mention uglify, typescript, flow and the others I assume would fall into this category. Is sweetJS even a parser? I think you should separate these two classes of parsers in some way. Either only focus on the esprima-inspired parsers or lump them together in some way, because they have the same base APIs, etc.

**Comment by mikesherov** [comment]
espree is a thin wrapper around acorn at this point. I wouldn't include it in the list of parsers.

Really, it's Esprima / Acorn / Babylon. 2 out of the 3 conform to ESTree

**Comment by xjamundx** [comment]
Yeah I think that's fair. It's really a short list. I know the babel folks had some reasons for breaking with the pack on the tree shape, but I wasn't in any way involved with those discussions.

**Comment by mikesherov** [comment]
There wasn't really a discussion. Babel felt they could do transforms easier with a few tweaks to the format, and that was that. Interop didn't seem to be a main concern.
